### PR TITLE
fix: GOCQ适配器的GetGroupInfo函数无法正常工作

### PR DESCRIPTION
**Pull request by Fripine**
#718 由于该函数在当前版本中没有调用，故此次修正不会影响当前版本的运行，为后续新功能开发考虑，先行提请修正该函数使其正常工作

### CODE REVIEW

**Comment by fy0** [comment]
SYO15~}F{3GPIQ33 $LJ)MP
当初就应该把这类玩意封装成异步调用
请问在群里吗，我们在qq上有一个海豹烹饪群要不要加入

**Review by fy0 — APPROVED** [review]

**Comment by Fripine** [comment]
> SYO15~}F{3GPIQ33 $LJ)MP [ SYO15~}F{3GPIQ33 $LJ)MP ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4) [ ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4) 当初就应该把这类玩意封装成异步调用 请问在群里吗，我们在qq上有一个海豹烹饪群要不要加入

烹饪群是哪个，我加了用户群

**Comment by fy0** [comment]
> > SYO15~}F{3GPIQ33 $LJ)MP
> >       
> >         [
> >           
> >             SYO15~}F{3GPIQ33 $LJ)MP
> >           
> >         ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4)
> >         
> >        [ SYO15~}F{3GPIQ33 $LJ)MP ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4)
> >       
> >         [
> >           
> >             SYO15~}F{3GPIQ33 $LJ)MP
> >           
> >         ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4)
> >         
> >        [ ](https://private-user-images.githubusercontent.com/1579850/322268664-cbb1c729-f5fe-4873-9d95-cf500ad9676f.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMwOTQ3MTYsIm5iZiI6MTcxMzA5NDQxNiwicGF0aCI6Ii8xNTc5ODUwLzMyMjI2ODY2NC1jYmIxYzcyOS1mNWZlLTQ4NzMtOWQ5NS1jZjUwMGFkOTY3NmYuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQxNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MTRUMTEzMzM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9Njg1N2RjNzVkNTYzZWNiYTNlM2U1M2Q2OWYzZjEwZTkwODU4ZTBjMjNkY2ViODJiNGI3ZDE2NGQwMTc4NDdlNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.e0ERuQEmy-2te4apDAEyvgFrR1IvPeKSMNzQ_8j_ME4) 当初就应该把这类玩意封装成异步调用 请问在群里吗，我们在qq上有一个海豹烹饪群要不要加入
> 
> 烹饪群是哪个，我加了用户群

在群里的id是啥，我拉你

**Comment by nodisease** [comment]
也可以加我我拉你

**Comment by Xiangze-Li** [comment]
@Fripine 这个PR已经是 approved 了，要合并吗？

**Comment by Fripine** [comment]
> @Fripine 这个PR已经是 approved 了，要合并吗？

好的，辛苦

**Comment by Xiangze-Li** [comment]
按木落的审核意见合并

**Pull request merged**
